name: Snapshot

on:
  workflow_dispatch:
  push:
  pull_request:

env:
  DOCKER_IMAGE_NAME: tiagoboeing/nodejs-github-actions

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Extract branch name
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v3.2.0
        with:
          push: true
          tags: ${{ env.DOCKER_IMAGE_NAME }}:${{ env.BRANCH_NAME }}-SNAPSHOT
          target: production
